package com.android.openpressing.utils

import com.android.openpressing.data.models.Requirement

const val BASE_URL = "http://192.168.43.23:1337"

const val ADMINISTRATOR_FEATURES = "/api/administrateurs"
const val AGENCY_FEATURES = "/api/agencies"
const val AGENCY_LAUNDRY_FEATURES = "/api/agency-laundries"
const val AGENCY_SERVICE_FEATURES = "/api/agency-services"
const val AGENT_FEATURES = "/api/agent"
const val ANNONCE_FEATURES = "/api/annonces"
const val CITY_FEATURES = "/api/cities"
const val CLIENT_FEATURES = "/api/clients"
const val COUNTRY_FEATURES = "/api/countries"
const val LAUNDRY_FEATURES = "/api/laundries"
const val LAUNDRY_CATEGORIE_FEATURES = "/api/laundry-categories"
const val LAUNDRY_TYPE_FEATURES = "/api/laundry-types"
const val MESSAGE_FEATURES = "/api/messages"
const val OFFER_FEATURES = "/api/offers"
const val ORDER_FEATURES = "/api/orders"
const val OWNER_FEATURES = "/api/proprietaires"
const val PRESSING_FEATURES = "/api/pressings"
const val PRIVILEGE_FEATURES = "/api/priveleges"
const val PROMOTION_FEATURES = "/api/promotions"
const val QUARTER_FEATURES = "/api/quarters"
const val REQUIREMENT_FEATURES = "/api/requirements"
const val REQUIREMENT_DETAIL_FEATURES = "/api/requirement-details"
const val SERVICE_FEATURES = "/api/services"
const val SERVICE_CATEGORY_FEATURES = "/api/service-categories"
const val SERVICE_TYPE_FEATURES = "/api/service-types"
const val USER_FEATURES = "/api/users"